on:
  schedule:
    - cron: "0 0 * * 5"
  push:
    branches: main

name: Render and Publish

# you need these permissions to publish to GitHub pages
# permissions:
#     contents: write
#     pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install Google Fonts
        run: |
          wget -O Noto_Sans.zip https://fonts.google.com/download?family=Noto%20Sans
          unzip -d Noto_Sans/ Noto_Sans.zip
          mv Noto_Sans /usr/share/fonts/
          fc-cache -fv

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true

      # add software dependencies here and any libraries

      # From https://github.com/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v3

      # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # See more at https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md

      - name: Install ubuntu dependencies
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+
          sudo apt update
          sudo apt install libudunits2-dev \
                           libcurl4-openssl-dev \
                           libgdal-dev \
                           gdal-bin \
                           libproj-dev
          sudo apt install r-cran-sf r-cran-rnaturalearthdata r-cran-terra

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::rmarkdown
            any::downlit
            any::knitr
            any::skimr
            any::sf
            any::rnaturalearthdata
            any::rnaturalearth
            any::ggplot2
            any::ggthemes
            any::devtools
            any::jsonlite
            any::yaml
            any::terra
            any::lubridate
            any::stringr
            any::dplyr
            any::tidyr
            any::purrr
            any::readr
            any::xml2

      - name: Install Python dependencies
        run: |
          pip install pandas datetime

      # NOTE: If Publishing to GitHub Pages, set the permissions correctly
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
        run: |
          git config --global user.email "svanderplas2@unl.edu"
          git config --global user.name "Auto Build 251 Site"
          quarto publish gh-pages docs --no-render --no-browser
